In [13]:
import matplotlib.pyplot as plt
import numpy as np
import random
import time

In [3]:
x = np.array([[3,6],[5,7]])
y = x.transpose()
print(y)

[[3 5]
 [6 7]]


In [6]:
import numpy as np
a = np.array([1, 2, 3])
b = a[:]


In [7]:
b == a

array([ True,  True,  True])

In [11]:
a is b

False

In [9]:
b[0] = 3

In [10]:
a

array([3, 2, 3])