In [2]:
import numpy as np
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [3]:
np.logspace(1, 2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [4]:
np.logspace(np.log10(250), np.log10(500), 10)

array([250.        , 270.01493472, 291.63225989, 314.98026247,
       340.19750004, 367.43362307, 396.85026299, 428.62199143,
       462.93735614, 500.        ])

In [5]:
X = np.array([[1,2,3], [4,5,6]])

In [6]:
X.shape

(2, 3)

In [7]:
X.size

6

In [25]:
x = np.random.random(10)

In [26]:
np.any(x > 0.9)

True

In [27]:
np.all(x >= 0.1)

True

In [28]:
x

array([0.80000816, 0.24721447, 0.49341149, 0.50756776, 0.36689291,
       0.39584089, 0.83298981, 0.84850683, 0.93266071, 0.35447033])

In [31]:
x = 20
not np.any([x%i == 0 for i in range(2, x)])
# Find whether x is prime.

False