In [1]:
import numpy as np

In [2]:
zero_vector = np.zeros(5)

In [4]:
zero_matrix = np.zeros((5,3))

In [5]:
zero_vector

array([0., 0., 0., 0., 0.])

In [6]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
x = np.array([1,2,3])

In [8]:
y = np.array([2,4,6])

In [9]:
[[1,3],[5,9]]

[[1, 3], [5, 9]]

In [10]:
np.array([[1,3],[5,9]])

array([[1, 3],
       [5, 9]])

In [11]:
A = np.array([[1,3],[5,9]])

In [13]:
A.transpose()

array([[1, 5],
       [3, 9]])

In [14]:
# True or False: a numpy array's length may be modified after being created.
# False

In [17]:
import numpy
numpy.array([0., 0., 0., 0., 0.])
# What code will produce that object?
# numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
x = numpy.array([[3,6],[5,7]])
y = x.transpose()
print(y)
# What does this print?
# array([[3 5],[6 7]])

[[3 5]
 [6 7]]
