In [1]:
import numpy as np
z1 = np.array([1,3,5,7,9])

In [2]:
z2 = z1 +1

In [3]:
z1

array([1, 3, 5, 7, 9])

In [4]:
z2

array([ 2,  4,  6,  8, 10])

In [5]:
ind = [0,2,3]

In [6]:
z1[ind]

array([1, 5, 7])

In [7]:
ind = np.array([0,2,3])

In [8]:
z1[ind]

array([1, 5, 7])

In [9]:
z1 = np.array([1,3,5,7,9])

In [10]:
z1 > 6

array([False, False, False,  True,  True])

In [11]:
z1[z1 > 6]

array([7, 9])

In [12]:
z2[z1 > 6]

array([ 8, 10])

In [13]:
ind = z1 > 6

In [14]:
ind

array([False, False, False,  True,  True])

In [15]:
z1[ind]

array([7, 9])

In [16]:
z2[ind]

array([ 8, 10])

In [18]:
z1 = np.array([1,3,5,7,9])

In [19]:
w = z1[0:3]

In [20]:
w

array([1, 3, 5])

In [21]:
w[0] = 3

In [22]:
w

array([3, 3, 5])

In [23]:
z1

array([3, 3, 5, 7, 9])

In [24]:
z1 = np.array([1,3,5,7,9])

In [26]:
ind = np.array([0,1,2])

In [27]:
z1

array([1, 3, 5, 7, 9])

In [28]:
ind

array([0, 1, 2])

In [29]:
w = z1[ind]

In [30]:
w

array([1, 3, 5])

In [32]:
w[0] = 3

In [33]:
w

array([3, 3, 5])

In [34]:
z1

array([1, 3, 5, 7, 9])

In [38]:
a = np.array([1,2])
b = np.array([3,4,5])
b[a]
# array([4, 5])

array([4, 5])

In [39]:
c = b[1:]
b[a] is c
# False

False